## 가상 AB 테스트 데이터 로딩하기

In [2]:
import psycopg2
import pandas as pd
import pandas.io.sql as sqlio
import math

# Redshift connection 함수
def get_Redshift_connection(autocommit):
    host = "learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com"
    redshift_user = "jico9954"
    redshift_pass = "Jico9954!1"
    port = 5439
    dbname = "dev"
    conn = psycopg2.connect("dbname={dbname} user={user} host={host} password={password} port={port}".format(
        dbname=dbname,
        user=redshift_user,
        password=redshift_pass,
        host=host,
        port=port
    ))
    conn.set_session(autocommit=autocommit)
    return conn

In [3]:
conn = get_Redshift_connection(True)
cur = conn.cursor()

#### user_event

In [6]:
sql = """SELECT * FROM raw_data.user_event"""
user_event = sqlio.read_sql_query(sql, conn)

/var/folders/yr/8q3yc9wn6ln3ypw1ry6kgf280000gn/T/ipykernel_21864/839491649.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  user_event = sqlio.read_sql_query(sql, conn)

In [8]:
user_event.head()

   user_id  datestamp  item_id  clicked  purchased  paidamount
0    89374 2019-01-11        1        0          0           0
1    89374 2019-01-11       10        1          0           0
2    89377 2019-01-11       74        0          0           0
3    89377 2019-01-11       17        0          0           0
4    89377 2019-01-11       31        0          0           0

In [9]:
user_event.describe()

,user_id,datestamp,item_id,clicked,purchased,paidamount
count,973202.000000,973202,973202.000000,973202.000000,973202.000000,973202.000000
mean,50191.475341,2019-01-14 00:54:22.140028672,49.450383,0.240476,0.046497,0.949829
min,0.000000,2019-01-11 00:00:00,0.000000,0.000000,0.000000,0.000000
25%,25176.000000,2019-01-12 00:00:00,24.000000,0.000000,0.000000,0.000000
50%,50432.000000,2019-01-14 00:00:00,49.000000,0.000000,0.000000,0.000000
75%,75180.000000,2019-01-16 00:00:00,74.000000,0.000000,0.000000,0.000000
max,99999.000000,2024-06-23 00:00:00,103.000000,1.000000,1.000000,77.000000
std,28878.365802,NaN,28.844863,0.427373,0.210559,4.978441

In [10]:
user_event.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 973202 entries, 0 to 973201
Data columns (total 6 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   user_id     973202 non-null  int64
 1   datestamp   973202 non-null  datetime64[ns]
 2   item_id     973202 non-null  int64
 3   clicked     973202 non-null  int64
 4   purchased   973202 non-null  int64
 5   paidamount  973202 non-null  int64
dtypes: datetime64[ns](1), int64(5)
memory usage: 44.5 MB

#### user_variant

In [11]:
sql = """SELECT * FROM raw_data.user_variant"""
user_variant = sqlio.read_sql_query(sql, conn)

/var/folders/yr/8q3yc9wn6ln3ypw1ry6kgf280000gn/T/ipykernel_21864/621177049.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  user_variant = sqlio.read_sql_query(sql, conn)

In [12]:
user_variant.head()

   user_id variant_id
0        1       test
1        3       test
2        5       test
3        7       test
4        9    control

In [13]:
user_variant.describe()

             user_id
count  100000.000000
mean    49999.500000
std     28867.657797
min         0.000000
25%     24999.750000
50%     49999.500000
75%     74999.250000
max     99999.000000

In [14]:
user_variant.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 2 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   user_id     100000 non-null  int64
 1   variant_id  100000 non-null  object
dtypes: int64(1), object(1)
memory usage: 1.5+ MB

#### user_metadata

In [15]:
sql = """SELECT * FROM raw_data.user_metadata"""
user_metadata = sqlio.read_sql_query(sql, conn)

/var/folders/yr/8q3yc9wn6ln3ypw1ry6kgf280000gn/T/ipykernel_21864/2891954023.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  user_metadata = sqlio.read_sql_query(sql, conn)

In [16]:
user_metadata.head()

   user_id    age     gender                 updated_at
0        0  50-up     female 2024-01-04 20:37:01.612992
1        1  50-up     female 2024-01-04 20:37:01.612992
2        4   0-19       male 2024-01-04 20:37:01.612992
3        5   0-19     female 2024-01-04 20:37:01.612992
4        6   0-19  undefined 2024-01-04 20:37:01.612992

In [17]:
user_metadata.describe()

             user_id                     updated_at
count  100000.000000                         100000
mean    49999.500000  2024-01-04 20:46:12.446407168
min         0.000000     2024-01-04 20:37:01.612992
25%     24999.750000     2024-01-04 20:37:01.612992
50%     49999.500000     2024-01-04 20:37:01.612992
75%     74999.250000     2024-01-04 20:37:01.612992
max     99999.000000            2024-06-23 08:01:08
std     28867.657797                            NaN

In [18]:
user_metadata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 4 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   user_id     100000 non-null  int64
 1   age         100000 non-null  object
 2   gender      100000 non-null  object
 3   updated_at  100000 non-null  datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(2)
memory usage: 3.1+ MB

## Look at analytics.variant_daily_sessions

In [19]:
"""
CREATE TABLE analytics.variant_daily_sessions AS
SELECT
    variant_id,
    user_id,
    datestamp,
    count(distinct item_id) num_of_items, -- 총 impression
    sum(clicked) num_of_clicks,                -- 총 click
    sum(purchased) num_of_purchases,  -- 총 purchase
    sum(paidamount) revenue                   -- 총 revenue
FROM raw_data.user_event ue
JOIN raw_data.user_variant uv ON ue.user_id = uv.user_id
GROUP by 1, 2, 3
"""

'\nCREATE TABLE analytics.variant_daily_sessions AS\nSELECT\n    variant_id,\n    user_id,\n    datestamp,\n    count(distinct item_id) num_of_items, -- 총 impression\n    sum(clicked) num_of_clicks,                -- 총 click\n    sum(purchased) num_of_purchases,  -- 총 purchase\n    sum(paidamount) revenue                   -- 총 revenue\nFROM raw_data.user_event ue\nJOIN raw_data.user_variant uv ON ue.user_id = uv.user_id\nGROUP by 1, 2, 3\n'

In [20]:
sql = """SELECT * FROM analytics.variant_daily_sessions"""
vds = sqlio.read_sql_query(sql, conn)

/var/folders/yr/8q3yc9wn6ln3ypw1ry6kgf280000gn/T/ipykernel_21864/22728043.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  vds = sqlio.read_sql_query(sql, conn)

In [21]:
vds.head()

,variant_id,user_id,datestamp,num_of_items,num_of_clicks,num_of_purchases,revenue
0,test,20343,2019-01-15,18,5,1,12
1,test,52740,2019-01-12,17,5,0,0
2,control,39613,2019-01-16,2,1,0,0
3,control,78657,2019-01-11,18,9,1,13
4,control,11479,2019-01-13,4,0,0,0

Equal Traffic?

In [22]:
vds.groupby('variant_id').size()

variant_id
control    82526
test       83117
dtype: int64

In [23]:
vds.groupby('variant_id')["user_id"].nunique()

variant_id
control    49861
test       50119
Name: user_id, dtype: int64

## Calculate z-score

### Revenue

In [24]:
vds.groupby('variant_id')["revenue"].mean()

variant_id
control    5.590990
test       5.570136
Name: revenue, dtype: float64

In [ ]:
vds.groupby('variant_id')["revenue"].sum()

variant_id
control    461402
test       462973
Name: revenue, dtype: int64

In [ ]:
vds.sort_values('user_id')

,variant_id,user_id,datestamp,num_of_items,num_of_clicks,num_of_purchases,revenue
54727,test,0,2019-01-11,6,3,1,25
105992,test,0,2019-01-14,3,1,0,0
147157,test,1,2019-01-11,2,1,0,0
62537,control,2,2019-01-17,3,0,0,0
148186,test,3,2019-01-12,3,0,0,0
...,...,...,...,...,...,...,...
92318,test,99997,2019-01-13,3,0,0,0
955,control,99998,2019-01-13,26,5,0,0
106199,control,99998,2019-01-12,9,3,0,0
159464,control,99999,2019-01-14,1,0,0,0
61107,control,99999,2019-01-13,4,1,0,0

In [ ]:
vds["revenue_2x"] = vds["revenue"]*vds["revenue"]

In [ ]:
vds.groupby('variant_id')["revenue_2x"].mean()

variant_id
control    219.259967
test       217.957421
Name: revenue_2x, dtype: float64

In [ ]:
vds.groupby('variant_id')["revenue_2x"].sum()

variant_id
control    18094648
test       18115967
Name: revenue_2x, dtype: int64

### scipy.stats.ttest_ind를 이용한 t-score 계산

In [ ]:
from scipy import stats

In [ ]:
# control 그룹에 속한 매출액 정보를 numpy 배열로 받아오기
a = vds[vds["variant_id"]=="control"]["revenue"].to_numpy()
# test 그룹에 속한 매출액 정보를 numpy 배열로 받아오기
b = vds[vds["variant_id"]=="test"]["revenue"].to_numpy()
print(len(a), len(b))

82526 83117

In [ ]:
# control 그룹 매출액 정보 처음 100개 보기
a[0:100]

array([19, 37,  0, 11,  0, 43,  0, 19,  0,  0,  0,  0,  0,  0,  0,  0, 48,
        0, 16,  0, 11, 34, 33, 34, 13,  0,  0,  0,  0,  0,  0,  0,  0, 34,
        0, 11, 25,  0,  0,  0,  0, 62,  0, 16, 67,  0,  0,  0,  0,  0, 11,
        0,  0, 20, 16, 62,  0,  0, 13,  0,  0,  0, 28,  0, 13,  0,  0,  0,
       25,  0, 13, 32,  0,  0, 12,  0, 46,  0,  0, 13,  0,  0,  0, 20, 11,
       13,  0, 31, 28, 63,  0, 55,  0, 19,  0,  0,  0, 24, 52, 16])

In [ ]:
# test 그룹 매출액 정보 처음 100개 보기
b[0:100]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,  16,   0,  13,   0,
        38,   0,  37,  13,   0,   0,   0,  43,  77,  10,   0,   0,  25,
         0,  12,   0,   0,  13,  26,   0,   0, 119,   0,  13,   0,   0,
         0,   0,  13,  80,  27,   0,   0,  12,  40,   0,   0,  43,   0,
        13,  13,  25,   0,  12,   0,   0,   0,   0,   0,   0,  83,  11,
         0,  13,  60,   0,  19,  47,   0,  18,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,  11,   0,  38,   0,  12,   0,   0,   0,
        77,   0,  48,   0,   0,   0,  12,   0,   0])

In [ ]:
# ttest_ind 함수를 사용해서 두 그룹의 값들을 비교
# 이 함수는 t-score (사실상 z-score)와 p value를 계산해서 리턴해줌
t, p = stats.ttest_ind(b, a)
print(t, p)

-0.3099344058149316 0.7566112280419588

In [ ]:
# 나중에 사용하기 쉽게 함수로 구현
def compute_z_score(df, field_name):
  a = df[df["variant_id"]=="control"][field_name].to_numpy()
  b = df[df["variant_id"]=="test"][field_name].to_numpy()
  t, p = stats.ttest_ind(b, a)

  return t, p

In [ ]:
print(compute_z_score(vds, "revenue"))

(-0.3099344058149316, 0.7566112280419588)

### 직접 t-score 계산해보기

 - 그룹별로 크기와 평균과 각 원소 제곱의 합을 알면 계산 가능
   - mean_b와 mean_a (평균)
   - n_b와 n_a (크기)
   - square_b와 square_a (제곱의 평균)
 - 먼저 variance(표준편차의 제곱)은 아래와 같이 계산
   - var_b = square_b - mean_b*mean_b
   - var_a = square_a - mean_a*mean_a
 - 최종 t-score는 아래와 같이 계산
   - (mean_b - mean_a)/math.sqrt(var_b/n_b + var_a/n_a)

In [ ]:
n_a = 82526
n_b = 83116
mean_a = 5.590990
mean_b = 5.570203
square_a = 219.259967
square_b = 217.960044

In [ ]:
import math

var_a = (square_a - mean_a*mean_a)
var_b = (square_b - mean_b*mean_b)
print(var_a, var_b)

188.0007978199 186.932882538791

In [ ]:
z_score = (mean_b - mean_a)/math.sqrt(var_a/n_a+var_b/n_b)
print(z_score)

-0.3089440714048208

In [ ]:
import numpy as np

n_a2 = len(a)
n_b2 = len(b)

mean_a2 = np.mean(a)
mean_b2 = np.mean(b)

var_a2 = np.var(a)
var_b2 = np.var(b)

In [ ]:
t_score2 = (mean_b2 - mean_a2)/math.sqrt(var_a2/n_a2+var_b2/n_b2)
print(t_score2)

-0.30993312168036846

## Impression, Click, Purchase

In [ ]:
print(compute_z_score(vds, 'num_of_items'))

(1.376898010038125, 0.16854564339542127)

In [ ]:
print(compute_z_score(vds, 'num_of_clicks'))

(1.2372896120038408, 0.21598133702078443)

In [ ]:
print(compute_z_score(vds, 'num_of_purchases'))

(-0.6231765686852798, 0.5331693556153361)

All the three z-scores fall in between -1.96 and 1.96; all the p-values are larger than 0.05.